
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 19;
  public static final int FROM = 8;
  public static final int SELECT = 7;
  public static final int DATETIME = 25;
  public static final int INT = 23;
  public static final int RPAREN = 13;
  public static final int CONTEO = 27;
  public static final int DECIMAL = 26;
  public static final int SEMI = 10;
  public static final int STAR = 9;
  public static final int ON = 21;
  public static final int AS = 22;
  public static final int LPAREN = 12;
  public static final int ID = 16;
  public static final int TABLE = 3;
  public static final int EQUALS = 28;
  public static final int VARCHAR = 24;
  public static final int STRING = 15;
  public static final int CREATE = 2;
  public static final int COMMA = 11;
  public static final int INSERT = 4;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int VALUES = 6;
  public static final int SET = 18;
  public static final int DOT = 29;
  public static final int error = 1;
  public static final int UPDATE = 17;
  public static final int JOIN = 20;
  public static final int INTO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CREATE",
  "TABLE",
  "INSERT",
  "INTO",
  "VALUES",
  "SELECT",
  "FROM",
  "STAR",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "STRING",
  "ID",
  "UPDATE",
  "SET",
  "WHERE",
  "JOIN",
  "ON",
  "AS",
  "INT",
  "VARCHAR",
  "DATETIME",
  "DECIMAL",
  "CONTEO",
  "EQUALS",
  "DOT"
  };
}

